server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://192.168.17.129:3306/dynamic_wesays?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#spring:
#  datasource:
#    master:
#      url: jdbc:mysql://192.168.140.1:3306/attendance?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
#      username: master
#      password: root
#      filters: log4j,wall,mergeStat
#      driver-class-name: com.mysql.cj.jdbc.Driver
#    slave:
#      url: jdbc:mysql://192.168.140.1:3306/attendance?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
#      username: wesays
#      password: root
#      filters: log4j,wall,mergeStat
#      driver-class-name: com.mysql.cj.jdbc.Driver
#  application:
#    name: mybatis-service

mybatis-plus:
  config-location: classpath:mybatis.xml
  mapper-locations: classpath*:com/wesays/**/xml/*Mapper.xml
  type-aliases-package: com.wesays.*.entity
  global-config:
    id-type: 0
    db-column-underline: false
    refresh-mapper: true


